### ISSUE TITLE
fewer points of maintenance

### ISSUE THREAD

**Issue by DanVanAtta** [williamdekryger/triplea-game.github.io#1]
Ideally the website will never require updating. If neither of us are granted admin to the website repository then the website *will* never be updated. So hopefully that will happen and we can get more admins to help out over the long run.

So off the bat, the news section should be dropped. It'll get out of date quickly and nobody will want to update it monthly. Even questionable if we will have news that often. If we want to highlight announcements, we can find other ways to do it.

Another item is the dependency on the game version in the download text. "Download tripleA" will be just as informative to a new user as the version number. Existing users likely followed a download link and are not even going through the front page.

**Comment by williamdekryger** [comment]
This entirely depends on whether I get admin access to the main repo.

**Comment by DanVanAtta** [comment]
There could be a couple of points not considered. 
- ultimately the most important resource we have on this open source project is labor. It's not even money, labor is the thing in the least supply. Anything we can do to allow people to work on on bugs, features, or anything that is not maintenance and upkeep, is a big win.

- the release process is becoming automated. We are on track to be capable to push an unstable release daily. Having yet one more point of maintenance when doing a release is a burden, there are already way too many places to update.

- be sure to think long term. 5 years from now, will you be able to on a days notice drop everything and be able to make some website updates? It won't be much effort, but it will get annoying to have to do so every so often, in addition you might be travelling, on vacation, generally unavailable. So if we can avoid a point of maintenance, we should. The item that needs to be maintained needs to have a really good reason to be that way - the cost of any item is the maintenance we're going to have to do for the following years. So by this last point, the total cost is not *that* great that nothing will ever be worth the cost, but we do need to be sure that any points of maintenance that need to be updated periodically are very well justified and avoided whenever possible.

**Comment by williamdekryger** [comment]
Ok, I see what you mean. We can continue talking on Trello.

> This issue pertains to content, and therefore has been moved to Trello: https://trello.com/c/uMDgSkek
