### ISSUE TITLE
Community Page

### ISSUE THREAD

**Issue by williamdekryger** [williamdekryger/triplea-game.github.io#10]
@ron-murhammer suggested a revamp of the Community page, in the spirit of the Contribute page, which I agree with. Please give ideas and suggestions.

**Comment by ron-murhammer** [comment]
I'm not a web designer at all but I think just some basic clean up to add some dividers between the different sections. Just a little more organization around the different community areas.

**Comment by williamdekryger** [comment]
Feature implemented in 2d2ce58315b6e6664671ebb11432f8cc120d9729
