### ISSUE TITLE
clarify goals and requirements

### ISSUE THREAD

**Issue by DanVanAtta** [williamdekryger/triplea-game.github.io#2]
Eventually this should get converted to a wiki page, but a requirements doc of what  we want exactly the website to do  will be useful. This issue is intended to be the start of that doc. It's rough for now, please brainstorm a bit of requirements and we'll see if we can come to an agreement on a list.

To start..

Goals:
- serve as an attractive place for new users to begin an initial engagement with the game
- hosting of static help content (so that content need not live in the forums)
- links to the various tripleA related entities that exist on the web
- page 1 google results when searching for "axis and allies"

**Comment by DanVanAtta** [comment]
Additional thought, the ultimate goal of the website I think is simply this:
- get new people to discover the game, download it, and learn how to play (and start playing)

This means optimize the website first for a brand new visitor, maybe someone who has never heard of tripleA. Ideally we can teach them the game in while they download it.

**Comment by williamdekryger** [comment]
Like it. You can email me the Markdown of any wiki pages you want added (won't make them here obviously).

**Comment by DanVanAtta** [comment]
Let's keep thinking about the  goals and requirements a bit. Close this issue when the goals and requirements from this issue (#2) have been  transcribed to a wiki page (wiki pages serve are relatively formal documentation)

Will do on sending you updates. I'll favor PR for a more detailed suggestion. For the moment the high level items are really the matters that need to be decided. We can fix up copy, clean up some English, but if we screw up the site navigation then we may never be able to fix it.
