### ISSUE TITLE
maps page

### ISSUE THREAD

**Issue by DanVanAtta** [williamdekryger/triplea-game.github.io#7]
"TripleA is very versatile and can be used for scenarios from Hannibal crossing the Alps to very futuristic and modern time periods. Here are a few examples of the most popular maps on TripleA. (A comprehensive download list can be found here)"

This text needs to be updated quite a bit, I can help with that with a PR at a later date potentially.

The intent of the map in its current form is a bit off. I would want/expect the page to be similar to the collage of maps on the first page, but potentially more detailed. Even possibly with a link for each individual map.

To start, I think we probably should clarify the goal and intent of this page.

Goal:
- show a preview of the various maps that exist in tripleA
- give a concept of scope, of which maps are in tripleA

It could make sense to have some information about how to build maps and so forth near the bottom of the page.

**Comment by williamdekryger** [comment]
You are right. In fact, I had not planned to use this page in the long term, but wanted to do something like this: https://atom.io/packages

**Comment by DanVanAtta** [comment]
the atom.io style looks very nice and appropriate. I could picture us having a thumbnail for the map image, would be pretty sweet.

**Comment by williamdekryger** [comment]
Discussion of page content permanently moved to: https://trello.com/c/sxZMspBB
