### ISSUE TITLE
website readme

### ISSUE THREAD

**Issue by DanVanAtta** [williamdekryger/triplea-game.github.io#8]
The readme file can likely go ahead and start looking like the one we would have with the organization repo.

The target audience of the repository readme are tripleA website admin's, potentially looking to update something after the website has not been updated in a year. Alternatively other audiences would be users who are came upon the github repository page somehow while looking for something else.

So I would have first section with a brief description that this is the project for the tripleA website, and give a link to the site. Then have a header section of how the site is built, how to test it. Do not include details on how to submit requests for updates to the site. We do not want the general internet public doing that..  For now the communication path for requesting updates I think is clear.

**Comment by williamdekryger** [comment]
The goal of the readme is for devs looking to contribute, not for the general public. I can add some more content, but I also want to be able to send people interested in helping even with content (like Zjelco or Cernel, or whoever) here to figure out how to do it without emailing me sixteen-hundred times.

**Comment by DanVanAtta** [comment]
That's about perfect. I recommend:
- dedicating one line at the top of the readme to state that this repo hosts the website, and "here is the link". The "lost" general public will hopefully just click that and then be on their way.

Otherwise exactly right the target audience are effectively devs. For this:
- try to be self effacing early on in the process. This avoids creating dependencies on you specifically, and starts community involvement and training early. One challenge is if you lead a project for too long, it can be too tough for others to pick it up, or be forced to pick it up, or it'll be just too easy for them to ask you to do everything. That can work and be fine for a while, but in the long run unless you are *really* dedicated, it might not be so pleasant.

- perhaps of more help, I'd recommend getting rid of alternatives processes presented in the readme. Instead of "submit a issue, *or* email me", I'd have one clear well defined process, namely to submit an issue. You'll probably get a 1000 emails anyways. Getting away from email is very good though, lower overhead and transparent. All in all, nothing can't be said on email that can't just also be submitted into an issue as well. If someone is more capable then submitting a full PR likely best even (letting other people do as much work as possible and not relying on central bottlenecks to do so is very good for project scaling and maintenance, overall velocity effectively).

- so more what I'm getting at, I'd focus on more removing content, having a clear single path and process for various actions. All in all, I would remove any process items that are either triggered by or rely upon email and/or that name you specifically by name.

**Comment by williamdekryger** [comment]
Ok, I agree. It can be shortened and stuff removed. I wonder if it would be helpful to track the editorial process on [Trello](http://trello.com/), and keep development stuff in the issues here. Thoughts?

**Comment by DanVanAtta** [comment]
I've no objections to Trello for the copy editing type of stuff.

There is a start to a git tutorial page that was made for the game engine here: https://github.com/triplea-game/triplea/wiki/DevSetup--Git-Workflow.  I hope it can be cleaned up a bit more in the short term, but we can link to that in ReadMe to help keep people in the git framework as much as possible and avoiding email.

**Comment by williamdekryger** [comment]
Issue addressed in cffa9957099f5033abb8d53d4c1a5deb4f36d5c7.
