### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by doctored** [williamdekryger/triplea-game.github.io#9]
seeing some issue at the standard iPhone viewport sizes images attached:

<img width="394" alt="screen shot 2015-09-23 at 7 34 27 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064152/53238824-622a-11e5-826b-d78c15441cd1.png">
<img width="404" alt="screen shot 2015-09-23 at 7 34 08 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064153/53429048-622a-11e5-802d-7cda07f830cc.png">
<img width="416" alt="screen shot 2015-09-23 at 7 34 39 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064155/537012a2-622a-11e5-9cb3-38abc6d33d83.png">
<img width="414" alt="screen shot 2015-09-23 at 7 34 50 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064151/53117e72-622a-11e5-89b0-14a2e8f3de7d.png">
<img width="444" alt="screen shot 2015-09-23 at 7 35 05 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064154/53486bd0-622a-11e5-8ae6-192c86dc0fbe.png">
<img width="442" alt="screen shot 2015-09-23 at 7 35 14 pm" src="https://cloud.githubusercontent.com/assets/4541889/10064150/5263cd40-622a-11e5-8fc3-c1ddfd428de6.png">

**Comment by williamdekryger** [comment]
Right. Well, actually, when I was coding the layout, I used semi responsive techniques for most things, as you can see (The images and content mostly scaled well). It is a matter of getting a mobile stylesheet to fix up floats on the footer and the menu, as well as diminishing the font size of the title. Already in the works.
